import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Generate PDF from an element
export const exportToPDF = async (elementId, filename, options = {}) => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  const {
    scale = 2,
    margin = 20,
    format = 'a4',
    orientation = 'portrait'
  } = options;

  // Capture the element as canvas
  const canvas = await html2canvas(element, {
    scale,
    useCORS: true,
    allowTaint: true,
    backgroundColor: '#141210',
    logging: false
  });

  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF({
    orientation,
    unit: 'mm',
    format
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  const imgWidth = pageWidth - (margin * 2);
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  // Add image to PDF (may span multiple pages)
  let y = margin;
  const maxHeight = pageHeight - (margin * 2);
  
  if (imgHeight <= maxHeight) {
    pdf.addImage(imgData, 'PNG', margin, y, imgWidth, imgHeight);
  } else {
    // Multi-page support
    let remainingHeight = imgHeight;
    let sourceY = 0;
    
    while (remainingHeight > 0) {
      const sliceHeight = Math.min(remainingHeight, maxHeight);
      const sliceRatio = sliceHeight / imgHeight;
      
      pdf.addImage(imgData, 'PNG', margin, y, imgWidth, imgHeight, undefined, 'FAST', 0);
      
      remainingHeight -= maxHeight;
      if (remainingHeight > 0) {
        pdf.addPage();
        y = margin;
      }
      sourceY += sliceHeight;
    }
  }

  pdf.save(`${filename}.pdf`);
  return true;
};

// Generate PDF from recipe data
export const exportRecipeToPDF = (recipe) => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header
  pdf.setFillColor(20, 18, 16);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  pdf.setTextColor(232, 89, 47);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(recipe.name || 'Recipe', margin, 28);
  
  pdf.setTextColor(148, 163, 184);
  pdf.setFontSize(10);
  pdf.text('Food Truck Launch Pad', pageWidth - margin, 28, { align: 'right' });
  
  y = 55;

  // Recipe Stats
  pdf.setTextColor(100, 116, 139);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  const stats = [
    `Prep: ${recipe.prep_time || 45} mins`,
    `Cook: ${Math.floor((recipe.cook_time || 720) / 60)} hours`,
    `Yield: ${recipe.batch_yield || 24} servings`,
    `Cost: $${recipe.cost_per_serving || '5.17'}/serving`
  ];
  pdf.text(stats.join('  •  '), margin, y);
  y += 15;

  // Ingredients Section
  pdf.setTextColor(232, 89, 47);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('INGREDIENTS', margin, y);
  y += 8;

  pdf.setTextColor(226, 232, 240);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');

  (recipe.ingredients || []).forEach((ing) => {
    const line = `• ${ing.name} - ${ing.qty} ${ing.unit} ($${ing.total?.toFixed(2) || '0.00'})`;
    pdf.text(line, margin, y);
    y += 6;
  });
  y += 10;

  // Method Section
  pdf.setTextColor(232, 89, 47);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('METHOD', margin, y);
  y += 8;

  pdf.setTextColor(226, 232, 240);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');

  (recipe.steps || []).forEach((step, i) => {
    // Check if we need a new page
    if (y > 270) {
      pdf.addPage();
      y = margin;
    }
    
    pdf.setTextColor(232, 89, 47);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Step ${i + 1}: ${step.title}`, margin, y);
    y += 6;
    
    pdf.setTextColor(100, 116, 139);
    pdf.setFontSize(9);
    pdf.text(`Time: ${step.time} | Temp: ${step.temp}`, margin, y);
    y += 5;
    
    pdf.setTextColor(226, 232, 240);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    // Word wrap content
    const lines = pdf.splitTextToSize(step.content, pageWidth - (margin * 2));
    lines.forEach(line => {
      if (y > 280) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, margin, y);
      y += 5;
    });
    y += 8;
  });

  // Footer
  pdf.setTextColor(100, 116, 139);
  pdf.setFontSize(8);
  pdf.text(`Generated by Food Truck Launch Pad • ${new Date().toLocaleDateString()}`, margin, 290);

  pdf.save(`${(recipe.name || 'recipe').toLowerCase().replace(/\s+/g, '-')}.pdf`);
  return true;
};

// Generate PDF from kitchen layout
export const exportKitchenLayoutToPDF = async (layoutData, canvasElement) => {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;

  // Header
  pdf.setFillColor(20, 18, 16);
  pdf.rect(0, 0, pageWidth, 25, 'F');
  
  pdf.setTextColor(232, 89, 47);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Kitchen Layout Design', margin, 17);
  
  pdf.setTextColor(148, 163, 184);
  pdf.setFontSize(10);
  pdf.text('Food Truck Launch Pad', pageWidth - margin, 17, { align: 'right' });

  // Capture canvas if provided
  if (canvasElement) {
    try {
      const canvas = await html2canvas(canvasElement, {
        scale: 2,
        backgroundColor: '#0F172A',
        logging: false
      });
      
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = pageWidth - (margin * 2) - 80; // Leave room for legend
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', margin, 35, imgWidth, Math.min(imgHeight, pageHeight - 60));
    } catch (e) {
      console.error('Failed to capture canvas:', e);
    }
  }

  // Equipment List (right side)
  const listX = pageWidth - 75;
  let y = 35;

  pdf.setTextColor(232, 89, 47);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Equipment List', listX, y);
  y += 8;

  pdf.setTextColor(226, 232, 240);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');

  let totalCost = 0;
  (layoutData.equipment || []).forEach((item) => {
    pdf.text(`• ${item.name}`, listX, y);
    y += 4;
    pdf.setTextColor(100, 116, 139);
    pdf.text(`  $${item.price?.toLocaleString() || '0'}`, listX, y);
    y += 5;
    pdf.setTextColor(226, 232, 240);
    totalCost += (item.price || 0);
  });

  y += 5;
  pdf.setTextColor(232, 89, 47);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total: $${totalCost.toLocaleString()}`, listX, y);

  // Footer
  pdf.setTextColor(100, 116, 139);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated ${new Date().toLocaleDateString()}`, margin, pageHeight - 10);

  pdf.save('kitchen-layout.pdf');
  return true;
};

export default { exportToPDF, exportRecipeToPDF, exportKitchenLayoutToPDF };

// CSV download utility
export const exportRowsToCSV = (rows, filename = 'export.csv') => {
  if (!rows || !rows.length) return;
  const headers = Object.keys(rows[0]);
  const escape = (v) => {
    const s = v == null ? '' : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [
    headers.join(','),
    ...rows.map((r) => headers.map((h) => escape(r[h])).join(',')),
  ].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// File -> base64 dataURL with size validation
export const fileToDataUrl = (file, maxBytes = 2 * 1024 * 1024) =>
  new Promise((resolve, reject) => {
    if (!file) return reject(new Error('No file selected'));
    if (file.size > maxBytes) {
      return reject(new Error(`File exceeds ${(maxBytes / 1024 / 1024).toFixed(1)}MB limit`));
    }
    const reader = new FileReader();
    reader.onload = (e) => resolve(e.target?.result);
    reader.onerror = () => reject(new Error('Failed to read file'));
    reader.readAsDataURL(file);
  });
